#!/usr/bin/env python3

import os
import html
import pandas as pd

from datetime import datetime


# ==================================================
# Configuration
# ==================================================

RUN_DATE = datetime.now().strftime("%Y-%m-%d")

ARC_DIR = os.path.join(
    "reports",
    "arc",
    RUN_DATE
)

os.makedirs(
    ARC_DIR,
    exist_ok=True
)


# ==================================================
# Security Knowledge Base
# ==================================================

KNOWLEDGE_BASE = {

    "CWE-89": {
        "impact":
            "Potential database manipulation, disclosure of sensitive information, "
            "and unauthorized access.",

        "action":
            "Replace dynamic SQL with parameterized queries or prepared statements. "
            "Validate all database inputs and avoid constructing SQL statements "
            "through string concatenation.",

        "testing":
            "Validate search, insert, update, and delete workflows. "
            "Test parameter handling and confirm malicious SQL input cannot alter "
            "database queries. Re-run Snyk and Rapid7 scans."
    },

    "CWE-79": {
        "impact":
            "Potential execution of malicious client-side scripts, "
            "session compromise, and unauthorized actions performed "
            "in a victim's browser.",

        "action":
            "Implement context-appropriate output encoding and input validation. "
            "Avoid rendering untrusted content as executable HTML or JavaScript. "
            "Use a restrictive Content Security Policy where appropriate.",

        "testing":
            "Test reflected, stored, and DOM-based XSS scenarios. "
            "Validate encoded output in all affected rendering contexts. "
            "Re-run Snyk and Rapid7 scans."
    },

    "CWE-22": {
        "impact":
            "Potential unauthorized access to files and directories "
            "outside intended application locations.",

        "action":
            "Normalize and validate file paths. Restrict file access to approved "
            "directories and prevent user-controlled input from selecting arbitrary "
            "filesystem locations.",

        "testing":
            "Test path traversal payloads using encoded and alternate path formats. "
            "Verify unauthorized files cannot be read, modified, or deleted."
    },

    "CWE-798": {
        "impact":
            "Credentials may be exposed in source code or application artifacts "
            "and could be used to gain unauthorized access.",

        "action":
            "Move credentials to an approved secrets-management solution. "
            "Remove hard-coded credentials from source code and rotate any "
            "credentials that may have been exposed.",

        "testing":
            "Verify application functionality after secret rotation. "
            "Confirm credentials are no longer present in source code, "
            "build artifacts, or repositories."
    }
}


DEFAULT_KB = {
    "impact":
        "Review the finding with the application owner and Security Engineering "
        "to determine the applicable business and security impact.",

    "action":
        "Review the finding-specific remediation guidance and implement the "
        "appropriate application security control.",

    "testing":
        "Re-run applicable Snyk and Rapid7 security scans, perform regression "
        "testing, and verify that the vulnerability is no longer reproducible."
}


# ==================================================
# Helpers
# ==================================================

def clean_value(value, default=""):
    """
    Safely convert pandas values to strings.
    """
    if pd.isna(value):
        return default

    value = str(value).strip()

    return value if value else default


def get_kb(cwe):
    """
    Return the security knowledge-base entry for a CWE.
    """

    cwe_string = clean_value(cwe).upper()

    if not cwe_string:
        return DEFAULT_KB

    for key, value in KNOWLEDGE_BASE.items():

        if key.upper() in cwe_string:
            return value

    return DEFAULT_KB


def get_row_validation(row, kb):
    """
    Prefer validation generated by the risk-report stage.
    Fall back to the knowledge base when unavailable.
    """

    validation = clean_value(
        row.get("VALIDATION")
    )

    if validation:
        return validation

    return kb["testing"]


def get_row_action(row, kb):
    """
    Prefer remediation generated by the risk-report stage.
    Fall back to the knowledge base when unavailable.
    """

    action = clean_value(
        row.get("RECOMMENDED_ACTION")
    )

    if action:
        return action

    action = clean_value(
        row.get("ACTION")
    )

    if action:
        return action

    return kb["action"]


def safe_count(value):
    """
    Safely convert occurrence counts to integers.
    """

    try:
        return int(float(value))
    except (TypeError, ValueError):
        return 0


def priority_rank(value):

    priority = clean_value(value).upper()

    return {
        "CRITICAL": 1,
        "HIGH": 2,
        "MEDIUM": 3,
        "LOW": 4
    }.get(priority, 99)


def overall_risk(df):

    priorities = (
        df["PRIORITY"]
        .fillna("")
        .astype(str)
        .str.upper()
    )

    if "CRITICAL" in priorities.values:
        return "CRITICAL"

    if "HIGH" in priorities.values:
        return "HIGH"

    if "MEDIUM" in priorities.values:
        return "MEDIUM"

    if "LOW" in priorities.values:
        return "LOW"

    return "UNKNOWN"


def html_value(value):
    """
    HTML escape arbitrary finding data.
    """

    return html.escape(
        clean_value(value)
    ).replace(
        "\n",
        "<br>"
    )


def html_pre(value):
    """
    HTML escape multiline path/URL data.
    """

    return html.escape(
        clean_value(value)
    )


# ==================================================
# Discover Prioritized Reports
# ==================================================

prioritized_reports = sorted(
    file
    for file in os.listdir(ARC_DIR)
    if file.endswith(
        "-prioritized-findings.csv"
    )
)

if not prioritized_reports:

    print(
        "No prioritized findings reports found."
    )

    raise SystemExit(0)


print()
print("=" * 60)
print(f"ARC_DIR: {ARC_DIR}")
print(
    f"Prioritized Reports Found: "
    f"{len(prioritized_reports)}"
)

for file in prioritized_reports:
    print(f"  {file}")

print("=" * 60)
print()


# ==================================================
# Process Each Application
# ==================================================

for report_file in prioritized_reports:

    INPUT_FILE = os.path.join(
        ARC_DIR,
        report_file
    )

    APP_NAME = (
        report_file
        .replace(
            "-prioritized-findings.csv",
            ""
        )
    )

    MD_OUTPUT = os.path.join(
        ARC_DIR,
        f"{APP_NAME}-remediation-package.md"
    )

    HTML_OUTPUT = os.path.join(
        ARC_DIR,
        f"{APP_NAME}-remediation-package.html"
    )

    print()
    print("=" * 60)
    print(
        f"Processing: {APP_NAME}"
    )
    print("=" * 60)

    # ==================================================
    # Load Data
    # ==================================================

    print(
        f"Loading {INPUT_FILE}"
    )

    df = pd.read_csv(
        INPUT_FILE
    )

    if df.empty:

        print(
            f"{APP_NAME}: No prioritized findings available."
        )

        continue

    required_columns = [
        "TITLE",
        "SOURCE",
        "PRIORITY",
        "OCCURRENCES"
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing_columns:

        raise Exception(
            f"{APP_NAME}: Missing required columns: "
            f"{missing_columns}"
        )

    print(
        f"Total Prioritized Findings Loaded: {len(df)}"
    )


    # ==================================================
    # Normalize Data
    # ==================================================

    df["PRIORITY"] = (
        df["PRIORITY"]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    df["TITLE"] = (
        df["TITLE"]
        .fillna("Unnamed Finding")
        .astype(str)
    )

    df["SOURCE"] = (
        df["SOURCE"]
        .fillna("Unknown")
        .astype(str)
    )

    df["OCCURRENCES"] = (
        pd.to_numeric(
            df["OCCURRENCES"],
            errors="coerce"
        )
        .fillna(0)
        .astype(int)
    )


    # ==================================================
    # Preserve Original Counts
    # ==================================================

    raw_finding_count = len(df)

    critical_count = (
        df["PRIORITY"]
        .str.upper()
        .eq("CRITICAL")
        .sum()
    )

    high_count = (
        df["PRIORITY"]
        .str.upper()
        .eq("HIGH")
        .sum()
    )

    medium_count = (
        df["PRIORITY"]
        .str.upper()
        .eq("MEDIUM")
        .sum()
    )

    low_count = (
        df["PRIORITY"]
        .str.upper()
        .eq("LOW")
        .sum()
    )


    # ==================================================
    # Select Critical / High
    # ==================================================

    remediation_df = df[
        df["PRIORITY"]
        .str.upper()
        .isin(
            [
                "CRITICAL",
                "HIGH"
            ]
        )
    ].copy()

    priority_finding_count = len(
        remediation_df
    )

    print(
        f"Critical Findings: {critical_count}"
    )

    print(
        f"High Findings: {high_count}"
    )

    print(
        f"Medium Findings: {medium_count}"
    )

    print(
        f"Low Findings: {low_count}"
    )

    print(
        f"Critical/High Remediation Items: "
        f"{priority_finding_count}"
    )


    # ==================================================
    # Sort
    # ==================================================

    remediation_df["RANK"] = (
        remediation_df["PRIORITY"]
        .apply(priority_rank)
    )

    remediation_df = remediation_df.sort_values(
        by=[
            "RANK",
            "OCCURRENCES"
        ],
        ascending=[
            True,
            False
        ]
    )


    # ==================================================
    # Overall Risk
    # ==================================================

    risk_df = df.copy()

    overall_risk_value = overall_risk(
        risk_df
    )


    # ==================================================
    # Markdown Header
    # ==================================================

    markdown = f"""# Application Remediation Package

## Application

{APP_NAME}

## Overall Risk

**{overall_risk_value}**

## Scope

This remediation package contains **Critical and High severity findings** requiring immediate developer and application-owner review.

Medium and Low findings remain part of the application's overall security posture but are excluded from the immediate remediation package.

---

## Risk Summary

| Priority | Findings |
|---|---:|
| Critical | {critical_count} |
| High | {high_count} |
| Medium | {medium_count} |
| Low | {low_count} |

### Findings Reviewed

- Raw prioritized findings reviewed: {raw_finding_count}
- Critical findings requiring action: {critical_count}
- High findings requiring action: {high_count}
- Immediate remediation items: {priority_finding_count}

---

# Critical / High Findings

"""


    # ==================================================
    # Finding Details
    # ==================================================

    if remediation_df.empty:

        markdown += """
No Critical or High findings are currently present in the prioritized report.

"""

    else:

        for index, row in remediation_df.iterrows():

            kb = get_kb(
                row.get("CWE")
            )

            title = clean_value(
                row.get("TITLE"),
                "Unnamed Finding"
            )

            priority = clean_value(
                row.get("PRIORITY"),
                "UNKNOWN"
            )

            source = clean_value(
                row.get("SOURCE"),
                "Unknown"
            )

            cwe = clean_value(
                row.get("CWE")
            )

            occurrences = safe_count(
                row.get("OCCURRENCES")
            )

            remediation_scope = clean_value(
                row.get(
                    "REMEDIATION_SCOPE"
                )
            )

            file_count = safe_count(
                row.get(
                    "FILE_COUNT"
                )
            )

            url_count = safe_count(
                row.get(
                    "URL_COUNT"
                )
            )

            top_directories = clean_value(
                row.get(
                    "TOP_DIRECTORIES"
                )
            )

            affected_files = clean_value(
                row.get(
                    "AFFECTED_FILES"
                )
            )

            affected_urls = clean_value(
                row.get(
                    "AFFECTED_URLS"
                )
            )

            description = clean_value(
                row.get(
                    "DESCRIPTION"
                )
            )

            action = get_row_action(
                row,
                kb
            )

            validation = get_row_validation(
                row,
                kb
            )

            markdown += f"""
## {index + 1}. {title}

### Priority

**{priority}**

### Source

{source}

### CWE

{cwe if cwe else "Not specified"}

### Occurrences

{occurrences}

### Remediation Scope

{remediation_scope if remediation_scope else "Not specified"}

### Files Affected

{file_count}

### URLs Affected

{url_count}

### Primary Application Areas

{top_directories if top_directories else "Not specified"}

### Business / Security Impact

{kb["impact"]}

"""

            if description:

                markdown += f"""
### Finding Description

{description}

"""

            markdown += f"""
### Developer Action

{action}

### Files Requiring Review

{affected_files if affected_files else "No file paths provided."}

### URLs Requiring Validation

{affected_urls if affected_urls else "No URLs provided."}

### Validation Requirements

{validation}

---

"""


    # ==================================================
    # Security Engineering Notes
    # ==================================================

    markdown += """
# Security Engineering Notes

The findings in this package represent the application's highest-priority remediation items based on the current prioritized security findings.

## Recommended Remediation Workflow

1. Address Critical findings first.
2. Address High findings second.
3. Identify the affected application components and owners.
4. Review the affected source code or runtime configuration.
5. Implement the recommended remediation.
6. Perform developer testing against the affected workflow.
7. Re-run Snyk scans for SAST findings.
8. Re-run Rapid7 authenticated scans for DAST findings.
9. Perform regression testing across affected business workflows.
10. Document any findings that require risk acceptance or compensating controls.
11. Obtain Security Engineering validation before closure.

## Validation Requirements

Each remediated finding should be validated using the following process:

- Confirm the vulnerable code or configuration has been changed.
- Confirm the original vulnerability can no longer be reproduced.
- Test the affected business workflow.
- Perform negative/security testing against the original attack condition.
- Re-run Snyk where source-code vulnerabilities are involved.
- Re-run Rapid7 where runtime/web application vulnerabilities are involved.
- Confirm the vulnerability is no longer reported or has been formally accepted.
- Document evidence of remediation and testing.

## Exit Criteria

A Critical or High finding should not be considered closed until:

- The remediation has been implemented.
- Developer testing has been completed.
- Required regression testing has passed.
- Snyk validation has been completed where applicable.
- Rapid7 validation has been completed where applicable.
- The vulnerability is no longer reproducible.
- Any residual risk has been documented.
- Security Engineering review has been completed.
- The finding has been formally closed or risk-accepted.

## Risk Acceptance

If remediation cannot be completed within the required timeframe, the application owner should document:

- Business justification.
- Residual security risk.
- Compensating controls.
- Planned remediation date.
- Responsible owner.
- Security Engineering approval.

"""


    # ==================================================
    # HTML Report
    # ==================================================

    html_output = f"""
<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<title>
{html.escape(APP_NAME)}
Application Remediation Package
</title>

<style>

body {{
    font-family: Arial, Helvetica, sans-serif;
    margin: 40px;
    color: #222;
    line-height: 1.5;
}}

h1 {{
    color: #003366;
}}

h2 {{
    color: #003366;
    border-bottom: 2px solid #dddddd;
    padding-bottom: 6px;
    margin-top: 35px;
}}

h3 {{
    color: #444;
}}

.summary {{
    background: #f5f7fa;
    border: 1px solid #ddd;
    padding: 20px;
    margin-bottom: 25px;
}}

.priority-critical {{
    color: #b71c1c;
    font-weight: bold;
}}

.priority-high {{
    color: #c62828;
    font-weight: bold;
}}

.finding {{
    border: 1px solid #cccccc;
    border-left: 6px solid #c62828;
    padding: 20px;
    margin-bottom: 30px;
    background: #ffffff;
}}

pre {{
    background: #f7f7f7;
    padding: 12px;
    overflow-x: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
}}

table {{
    border-collapse: collapse;
    width: 600px;
    max-width: 100%;
}}

th,
td {{
    border: 1px solid #cccccc;
    padding: 8px;
    text-align: left;
}}

th {{
    background-color: #eeeeee;
}}

</style>

</head>

<body>

<h1>Application Remediation Package</h1>

<h2>{html.escape(APP_NAME)}</h2>

<div class="summary">

<p>
<strong>Overall Risk:</strong>
{html.escape(overall_risk_value)}
</p>

<p>
<strong>Immediate Remediation Items:</strong>
{priority_finding_count}
</p>

<p>
<strong>Scope:</strong>
Critical and High severity findings
</p>

</div>

<h2>Risk Summary</h2>

<table>

<tr>
<th>Priority</th>
<th>Findings</th>
</tr>

<tr>
<td>Critical</td>
<td>{critical_count}</td>
</tr>

<tr>
<td>High</td>
<td>{high_count}</td>
</tr>

<tr>
<td>Medium</td>
<td>{medium_count}</td>
</tr>

<tr>
<td>Low</td>
<td>{low_count}</td>
</tr>

</table>

<h2>Critical / High Findings</h2>
"""


    # ==================================================
    # HTML Findings
    # ==================================================

    for index, row in remediation_df.iterrows():

        kb = get_kb(
            row.get("CWE")
        )

        title = clean_value(
            row.get("TITLE"),
            "Unnamed Finding"
        )

        priority = clean_value(
            row.get("PRIORITY"),
            "UNKNOWN"
        )

        source = clean_value(
            row.get("SOURCE"),
            "Unknown"
        )

        cwe = clean_value(
            row.get("CWE")
        )

        occurrences = safe_count(
            row.get("OCCURRENCES")
        )

        remediation_scope = clean_value(
            row.get("REMEDIATION_SCOPE")
        )

        file_count = safe_count(
            row.get("FILE_COUNT")
        )

        url_count = safe_count(
            row.get("URL_COUNT")
        )

        top_directories = clean_value(
            row.get("TOP_DIRECTORIES")
        )

        affected_files = clean_value(
            row.get("AFFECTED_FILES")
        )

        affected_urls = clean_value(
            row.get("AFFECTED_URLS")
        )

        action = get_row_action(
            row,
            kb
        )

        validation = get_row_validation(
            row,
            kb
        )

        priority_class = (
            "priority-critical"
            if priority.upper() == "CRITICAL"
            else "priority-high"
        )

        html_output += f"""

<div class="finding">

<h2>
{index + 1}. {html.escape(title)}
</h2>

<p>
<strong>Priority:</strong>
<span class="{priority_class}">
{html.escape(priority)}
</span>
</p>

<p>
<strong>Source:</strong>
{html.escape(source)}
</p>

<p>
<strong>CWE:</strong>
{html.escape(cwe or "Not specified")}
</p>

<p>
<strong>Occurrences:</strong>
{occurrences}
</p>

<p>
<strong>Remediation Scope:</strong>
{html.escape(remediation_scope or "Not specified")}
</p>

<p>
<strong>Files Affected:</strong>
{file_count}
</p>

<p>
<strong>URLs Affected:</strong>
{url_count}
</p>

<h3>Primary Application Areas</h3>

<pre>
{html_pre(top_directories or "Not specified")}
</pre>

<h3>Business / Security Impact</h3>

<p>
{html.escape(kb["impact"])}
</p>

<h3>Developer Action</h3>

<p>
{html.escape(action)}
</p>

<h3>Files Requiring Review</h3>

<pre>
{html_pre(affected_files or "No file paths provided.")}
</pre>

<h3>URLs Requiring Validation</h3>

<pre>
{html_pre(affected_urls or "No URLs provided.")}
</pre>

<h3>Validation Requirements</h3>

<p>
{html.escape(validation)}
</p>

</div>

"""


    # ==================================================
    # HTML Engineering Notes
    # ==================================================

    html_output += """

<h2>Security Engineering Notes</h2>

<p>
The findings in this package represent the application's
highest-priority remediation items based on the current
prioritized security findings.
</p>

<h3>Recommended Remediation Workflow</h3>

<ol>

<li>Address Critical findings first.</li>

<li>Address High findings second.</li>

<li>Identify affected application components and owners.</li>

<li>Review affected source code or runtime configuration.</li>

<li>Implement the recommended remediation.</li>

<li>Perform developer testing against the affected workflow.</li>

<li>Re-run Snyk scans for SAST findings.</li>

<li>Re-run Rapid7 authenticated scans for DAST findings.</li>

<li>Perform regression testing across affected business workflows.</li>

<li>Document findings requiring risk acceptance or compensating controls.</li>

<li>Obtain Security Engineering validation before closure.</li>

</ol>

<h3>Validation Requirements</h3>

<ul>

<li>Confirm the vulnerable code or configuration has been changed.</li>

<li>Confirm the original vulnerability can no longer be reproduced.</li>

<li>Test the affected business workflow.</li>

<li>Perform negative/security testing against the original attack condition.</li>

<li>Re-run Snyk where source-code vulnerabilities are involved.</li>

<li>Re-run Rapid7 where runtime/web application vulnerabilities are involved.</li>

<li>Confirm the vulnerability is no longer reported or has been formally accepted.</li>

<li>Document evidence of remediation and testing.</li>

</ul>

<h3>Exit Criteria</h3>

<ul>

<li>The remediation has been implemented.</li>

<li>Developer testing has been completed.</li>

<li>Required regression testing has passed.</li>

<li>Snyk validation has been completed where applicable.</li>

<li>Rapid7 validation has been completed where applicable.</li>

<li>The vulnerability is no longer reproducible.</li>

<li>Residual risk has been documented.</li>

<li>Security Engineering review has been completed.</li>

<li>The finding has been formally closed or risk-accepted.</li>

</ul>

<h3>Risk Acceptance</h3>

<p>
If remediation cannot be completed within the required timeframe,
the application owner should document the business justification,
residual security risk, compensating controls, planned remediation
date, responsible owner, and Security Engineering approval.
</p>

</body>

</html>
"""


    # ==================================================
    # Export
    # ==================================================

    with open(
        MD_OUTPUT,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
            markdown
        )

    with open(
        HTML_OUTPUT,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
            html_output
        )


    # ==================================================
    # Summary
    # ==================================================

    print()
    print("=" * 60)
    print(
        f"Application: {APP_NAME}"
    )
    print(
        f"Overall Risk: {overall_risk_value}"
    )
    print(
        f"Raw Findings Reviewed: "
        f"{raw_finding_count}"
    )
    print(
        f"Critical Findings: "
        f"{critical_count}"
    )
    print(
        f"High Findings: "
        f"{high_count}"
    )
    print(
        f"Remediation Items: "
        f"{priority_finding_count}"
    )
    print(
        f"Created: {MD_OUTPUT}"
    )
    print(
        f"Created: {HTML_OUTPUT}"
    )
    print("=" * 60)


print()
print("=" * 60)
print("Remediation package generation complete.")
print("=" * 60)
